// This file would normally be generated by FlutterFire CLI
// Placeholder until generated with proper Firebase configuration

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Updated Android configuration to match google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEMOeobzdIUiI3lP6OYqpDeflyDtGS-M8',
    appId: '1:258501172299:android:4ece1c0da4d9c2284d81ce',
    messagingSenderId: '258501172299',
    projectId: 'gymborn-6db05',
    storageBucket: 'gymborn-6db05.firebasestorage.app',
  );

  // Placeholder values - replace with actual project configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'placeholder',
    appId: 'placeholder',
    messagingSenderId: 'placeholder',
    projectId: 'gymborn-6db05',
    authDomain: 'gymborn-6db05.firebaseapp.com',
    storageBucket: 'gymborn-6db05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'placeholder',
    appId: 'placeholder',
    messagingSenderId: 'placeholder',
    projectId: 'gymborn-6db05',
    storageBucket: 'gymborn-6db05.firebasestorage.app',
    iosClientId: 'placeholder',
    iosBundleId: 'com.gymborn.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'placeholder',
    appId: 'placeholder',
    messagingSenderId: 'placeholder',
    projectId: 'gymborn-6db05',
    storageBucket: 'gymborn-6db05.firebasestorage.app',
    iosClientId: 'placeholder',
    iosBundleId: 'com.gymborn.app',
  );
}
